name: 02 Reusable Workflow

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify to Slack
      uses: ippanpeople/slack-notify-action@v0.0.4
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        thread_ts: "1753676783.810409"
        pretext: "STEP2: reusable workflow ✅ <!channel>"
        author_name: ":github_white: ${{ vars.AUTHOR_NAME }}"
        repository: "${{ vars.REPOSITORY }}"
        message: ":speech_balloon: (適宜変更してください)"
