# .github/workflows/convert.yml
name: Build Marp PDF

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Check input files
        run: |
          ls -l marp/slides
          ls -l marp/themes

      - name: Convert Marp to PDF
        run: |
          marp --version
          # marp --pdf --allow-local-files --verbose --theme-set marp/themes/sakura.css marp/slides/slide.md -o marp/slides/slide.pdf
          marp marp/slides/slide.md --theme marp/themes/sakura.css -o marp/slides/slide.pdf --pdf
          ls -l marp/slides

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: marp-pdf
          path: marp/slides/slide.pdf

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push PDF
        run: |
          git add marp/slides/slide.pdf
          git commit -m "chore: update slide.pdf [auto]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
