# .github/workflows/convert.yml
name: Build Marp PDF

on:
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Japanese/CJK fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Marp CLI
        run: npm install -g @marp-team/marp-cli

      - name: Build PDF from Marp slides
        working-directory: marp/slides
        run: |
          echo "=== Listing slides directory ==="
          ls -R .
          echo "=== Generating slide.pdf ==="
          marp slide.md \
            --theme ../themes \
            --allow-local-files \
            --pdf \
            -o slide.pdf
          echo "=== Resulting PDF ==="
          ls -l slide.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: marp-pdf
          path: marp/slides/slide.pdf

      - name: Commit and push generated PDF
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add marp/slides/slide.pdf
          git commit -m "chore: update slide.pdf [auto]" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }}
