name: First Step

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        run: |
          TS=$(date +%s)
          cat <<EOF > payload.json
          {
            "channel": "dev-インターン_ハンズオン",
            "attachments": [
              {
                "fallback": "ハンズオン Getting Started の通知",
                "color": "#215EBF",
                "pretext": "ハンズオン STEP0: Getting Started 完了✅ <!channel>",
                "author_name": ":github_white: :${{ vars.AUTHOR_NAME }}",
                "title": "Github Repository",
                "title_link": "${{ vars.REPOSITORY }}",
                "text": "Optional text that appears within the attachment",
                "footer": "インターン_ハンズオン BOT",
                "footer_icon": "https://qiita-user-contents.imgix.net/https%3A%2F%2Fqiita-image-store.s3.ap-northeast-1.amazonaws.com%2F0%2F1022001%2F30818b78-45d7-bac7-12b9-8433c2ef3011.png?ixlib=rb-4.0.0&auto=format&gif-q=60&q=75&s=035dfbe9921b278308e895b5e03dab1a",
                "ts": $TS
              }
            ]
          }
          EOF
            curl -X POST -H 'Content-type: application/json' \
              --data @payload.json \
              ${{ secrets.SLACK_WEBHOOK_URL }}
