name: First Step 02

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Notify to Slack
      uses: ippanpeople/slack-notify-action@v0.0.2
      with:
        webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        thread_ts: "1753676783.810409"
        author_name: "w-rin"
        repository: "https://github.com/ippanpeople/test"
        message: "hello world"
