name: Send Slack via Incoming Webhook

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Slack
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"username: getting start complete"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
